name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish-nuget:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/OneSearch.DataMapper
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - run: mkdir nupkgs
    - run: dotnet publish OneSearch.DataMapper.csproj -c Release
    - name: Pack
      run: dotnet pack OneSearch.DataMapper.csproj  -c Release --output nupkgs
    - name: Publish
      run: dotnet nuget push nupkgs/OneSearch.DataMapper.*.nupkg  -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json

